from . import test_automatic_provisioning
from . import test_campaign
from . import test_controller_registration
from . import test_foundation
from . import test_integration_api
from . import test_outbox
from . import test_result_inbox
from . import test_telephony_intent
from . import test_automation_results
