{
    "name": "Call Center Campaign",
    "version": "19.0.5.4.0",
    "category": "Sales/CRM",
    "summary": "Campaigns, teams, scripts, lifecycle, and automatic design control",
    "author": "Codestra",
    "license": "LGPL-3",
    "depends": ["call_center_core", "codestra_integration_hub", "phone_validation"],
    "data": [
        "security/provider_activity_security.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "security/automatic_provisioning_security.xml",
        "data/integration_nonce_cron.xml",
        "data/lifecycle_stages.xml",
        "data/lifecycle_stage_mappings.xml",
        "data/multi_business_master_data.xml",
        "data/campaign_mapping_projection.xml",
        "views/campaign_views.xml",
        "views/automatic_provisioning_views.xml",
        "views/foundation_views.xml",
        "views/script_views.xml",
        "views/crm_lead_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
